local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 7.5
   publish_frequency: 2.5
   width: 25.0
   height: 25.0
   resolution: 0.05
   static_map: false
   rolling_window: true